'use strict';(()=>{function m(f){var e=G[f];if(void 0!==e)return e.exports;e=G[f]={exports:{}};return I[f](e,e.exports,m),e.exports}var I={1623:()=>{$(function(){function f(){-1!==document.cookie.indexOf("".concat("Cascade.AuthSSO","\x3d"))&&(document.cookie="".concat("Cascade.AuthSSO","\x3d; expires\x3dThu, 01 Jan 1970 00:00:00 UTC;"))}function e(){var a=function(){var d=document.cookie.match(/(^|;\s*)(Cascade.AuthSSO)=([^;]*)/);return d?(d=parseInt(decodeURIComponent(d[3])),!isNaN(d)&&d>n.DefaultAttempted?
n.SharedStateAttempted:n.DefaultAttempted):n.NotAttempted}(),c=!(!window.msauthRpsShare||b.accountConstraint===w.AAD);if(a===n.NotAttempted||c&&a!==n.SharedStateAttempted)!function(d){$("#".concat("cascadeauthsso")).remove();var g=document.createElement("iframe");g.src=d;g.setAttribute("width","0");g.setAttribute("height","0");g.setAttribute("border","0");g.setAttribute("frameborder","0");g.setAttribute("style","display: none");g.id="cascadeauthsso";document.body.appendChild(g)}("".concat(b.baseUrl,
"/").concat(k.SilentAuth,"?auth\x3d").concat(b.silentAuthAction)),a=encodeURIComponent(c?n.SharedStateAttempted:n.DefaultAttempted),document.cookie="".concat("Cascade.AuthSSO","\x3d").concat(a,"; max-age\x3d").concat(1800,";")}function l(a){u=b.apiGeneration===v.Gen2?function(c){var d="webAadWithMsaProxy",g=!0,q=!0,p=!(!c||"msa"!=c.Type);b.accountConstraint==w.AAD?(d="webAadOnly",g=!1):b.accountConstraint==w.MSA?(d="webMsaOnly",q=!1):p&&(d="webMsaWithAadProxy");var t=encodeURIComponent(document.location.toString()),
x=encodeURIComponent(b?b.appCallbackUrl:document.location.toString()),H=c?c.DisplayName:null;p=c?{type:c.Type,memberName:c.EmailAddress,firstName:c.FirstName,lastName:c.LastName,cid:p?c.PassportCid:void 0,tenantId:c.TenantId,authenticatedState:"signedIn",displayName:H,orgName:H}:void 0;d={type:d,appSignInUrl:"".concat(b.baseUrl,"/").concat(k.SignIn),appSignInToUrl:"".concat(b.baseUrl,"/").concat(k.SignInTo),appSignOutUrl:"".concat(b.baseUrl,"/").concat(k.SignOut),appSwitchUrl:"".concat(b.baseUrl,
"/").concat(k.Switch),appSwitchToUrl:"".concat(b.baseUrl,"/").concat(k.SwitchTo),msa:g?{signOutAndForgetUrl:"".concat(b.baseUrl,"/").concat(k.SignOut),rememberedAccountsUrl:"https://login.live.com/Me.srf?wa\x3dwsignin1.0\x26rpsnv\x3d13\x26ct\x3d1544212396\x26rver\x3d6.7.6631.0\x26wp\x3dMBI_SSL\x26wreply\x3d".concat(t,"\x26id\x3d74335")}:void 0,aad:q?{signOutUrl:"https://login.microsoftonline.com/uxlogout?appid\x3d".concat(b.appId,"\x26wreply\x3d").concat(x,"\x26shouldForgetUser\x3dfalse"),signOutAndForgetUrl:"https://login.microsoftonline.com/uxlogout?appid\x3d".concat(b.appId,
"\x26wreply\x3d").concat(x,"\x26shouldForgetUser\x3dtrue"),forgetUrl:"https://login.microsoftonline.com/forgetuser",rememberedAccountsUrl:"https://login.microsoftonline.com/savedusers?appid\x3d".concat(b.appId,"\x26wreply\x3d").concat(x)}:void 0};return{meControlOptions:{apiGeneration:v.Gen2,appContextConfig:{commands:c&&c.Type===r.AAD&&window.AadMeControlOptions?window.AadMeControlOptions.commands:null},authProviderConfig:d,currentAccount:p}}}(a):function(c){var d,g,q,p,t=r.MSA;b.isConvergedStack?
(d="".concat(b.baseUrl,"/").concat(k.SignIn),g=q="".concat(b.baseUrl,"/").concat(k.SignOut),c&&(p=(t=c.Type)===r.MSA?c.PassportCid:c.Cid)):(d=b.signInUrl,g=b.msaSignOutUrl,q=b.aadSignOutUrl,c&&(t="OpenIdConnect"===c.AuthenticationType?r.AAD:r.MSA,p=c.PassportCid));return{meControlOptions:{apiGeneration:v.Gen1,rpData:{msaInfo:{signInUrl:d,signOutUrl:g},aadInfo:{signInUrl:d,signOutUrl:q},preferredIdp:b.preferredIdp},userData:c?{idp:t,memberName:c.EmailAddress,firstName:c.FirstName,lastName:c.LastName,
cid:p,authenticatedState:"1"}:void 0}}}(a);window.msCommonShell?window.msCommonShell.load(u):window.onShellReadyToLoad=function(){window.onShellReadyToLoad=null;window.msCommonShell.load(u)}}var y,z,A,B,C,D,E,h,w=function(a){return a[a.None=0]="None",a[a.MSA=1]="MSA",a[a.AAD=2]="AAD",a}({}),n=function(a){return a[a.NotAttempted=0]="NotAttempted",a[a.DefaultAttempted=1]="DefaultAttempted",a[a.SharedStateAttempted=2]="SharedStateAttempted",a}({}),r=function(a){return a.MSA="msa",a.AAD="aad",a}({}),
v=function(a){return a.Gen1="GEN1",a.Gen2="GEN2",a}({}),F=function(a){return a.Default="default",a.MsaFirst="msafirst",a.AadFirst="aadfirst",a.None="none",a}({}),u={},k={SignIn:"signin",SignInTo:"signinto",Switch:"switch",SwitchTo:"switchto",SignOut:"signout",SilentAuth:"silentauth"},b=(h=$(".meControl-configInfo")).length?{enabled:null!==(y=h.data("isenabled"))&&void 0!==y&&y,isConvergedStack:h.data("convergedstack"),silentAuthAction:null!==(z=h.data("silentauthaction"))&&void 0!==z?z:F.None,silentAuthRequireReload:null!==
(A=h.data("silentauthrequirereload"))&&void 0!==A&&A,isPublisher:null!==(B=window.msauthIsPublisher)&&void 0!==B&&B,apiGeneration:null!==(C=h.data("apigeneration"))&&void 0!==C?C:v.Gen1,appId:h.data("appid"),appCallbackUrl:h.data("appcallbackurl"),baseUrl:h.data("baseurl"),accountConstraint:h.data("accountconstraint"),preferredIdp:null!==(D=h.data("preferredidp"))&&void 0!==D?D:r.MSA,signInUrl:h.data("signinurl"),msaSignOutUrl:h.data("msasignouturl"),aadSignOutUrl:h.data("aadsignouturl")}:{enabled:!1,
isConvergedStack:!1,isPublisher:null!==(E=window.msauthIsPublisher)&&void 0!==E&&E,silentAuthAction:F.None};window.CascadeAuth={API:{silentAuthCallback:function(a){a&&(window.msauth?(f(),a.DisplayName=window.msauth.DisplayName,window.msauth=a):b.silentAuthRequireReload?location.reload():(f(),window.msauth=a,l(a)))},getUserInfo:function(){return window.msauth},getConfig:function(){return b},getShellOption:function(){return u},invokeSilentAuth:e,challengeUser:function(a){var c;if(b.isConvergedStack){if(a=
encodeURIComponent(null!==(c=a)&&void 0!==c?c:document.location.toString()),window.msauth){var d;c=null!==(d=window.msauth.EmailAddress)&&void 0!==d?d:"";a="".concat(b.baseUrl,"/").concat(k.SignInTo,"?ru\x3d").concat(a,"\x26login_hint\x3d").concat(encodeURIComponent(c),"\x26forcelogin\x3dtrue")}else a="".concat(b.baseUrl,"/").concat(k.SignIn,"?ru\x3d").concat(a,"\x26forcelogin\x3dtrue");location.href=a}},getSignInUrl:function(){return b.isConvergedStack?"".concat(b.baseUrl,"/").concat(k.SignIn):b.signInUrl}}};
b.enabled&&(window.msauth?(l(window.msauth),b.isConvergedStack&&f()):b.isPublisher?(l(void 0),b.isConvergedStack&&b.silentAuthAction!=F.None&&e()):window.UserInfoSingleton.getInstance().isConfigured()?window.UserInfoSingleton.getInstance().getUserInfo().then(function(a){window.msauth=a;l(a)},function(){window.msauth=void 0;l(void 0)}):l(void 0))})}},G={};m.n=f=>{var e=f&&f.__esModule?()=>f.default:()=>f;return m.d(e,{a:e}),e};m.d=(f,e)=>{for(var l in e)m.o(e,l)&&!m.o(f,l)&&Object.defineProperty(f,
l,{enumerable:!0,get:e[l]})};m.o=(f,e)=>Object.prototype.hasOwnProperty.call(f,e);m(1623)})();